server:
  port: 8030
spring:
  application:
    name: lime-sys-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    druid:
      url: jdbc:mysql://server.lemone.xyz:3306/lime
      username: lime
      password: Lime_mysql8
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false
