server:
  port: 8030

spring:
  output:
    ansi:
      enabled: detect
  application:
    name: @artifactId@
    version: @version@
  thymeleaf:
    cache: false
logging:
  level:
    root: WARN
    org.springframework.web: DEBUG



security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
