server:
  port: 8080

spring:
  application:
    name: lime-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
      - id: lime-sys-web
        uri: lb://lime-sys-web
        predicates:
        - Path=/api/**
